export default {
  logo: 'http://longfa-test.oss-cn-shenzhen.aliyuncs.com/6a906334fab5fa124556cac92a76ccbb8c7023d7dac001301d0083da0b3b8653.png',
  seal: 'http://longfa-test.oss-cn-shenzhen.aliyuncs.com/db8bfb67a5b977383e8f6f18b40b33a790a37471e10032bd79e7b73add7292a2.png',
  no: 'XSDD20250115000002',
  quoteNo: null,
  expireTime: null,
  nowComanyInfo: {
    name: '天津向云端科技有限公司',
  },
  outUserName: '制单人张三',
  saleUserName: '销售人员李四',
  customer: {
    id: 4,
    name: '绍登兴城有限公司',
    contact: '袁芳',
    mobile: '15628389265',
    telephone: null,
    email: null,
    fax: null,
    remark: null,
    status: 0,
    sort: 1,
    taxNo: '6561152521422T',
    taxPercent: 6,
    type: '0',
    bankName: '深圳建行',
    bankAccount: '154456424564245',
    bankAddress: null,
    deliveryAddress: '广东省深圳市龙华区xxx',
    createTime: 1_732_065_913_000,
    commonCategoryId: null,
  },
  supplier: {
    id: 1,
    name: '芋道源码',
    contact: '芋艿',
    mobile: null,
    telephone: '17321315478',
    email: null,
    fax: null,
    remark: null,
    status: null,
    sort: null,
    taxNo: null,
    taxPercent: null,
    bankName: null,
    bankAccount: null,
    bankAddress: null,
    type: null,
    allyRoleId: null,
    commonCategoryId: null,
    createTime: null,
  },
  orderTime: 1_736_905_067_000,
  deliveryTime: 1_736_905_067_000,
  totalCount: 9,
  totalPrice: 2564.68,
  totalProductPrice: 2389.08,
  totalTaxPrice: 310.58,
  discountPercent: 5,
  discountPrice: 134.98,
  deliveryAddress: null,
  remark: '',
  items: [
    {
      id: 68,
      productId: 2107,
      productUnitId: 22,
      productPrice: 216,
      orderProductPrice: 222.596_666_666_7,
      count: 3,
      discountPercent: 4,
      discountPrice: 25.92,
      taxPercent: 13,
      taxPrice: 80.87,
      totalPrice: 702.95,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '906',
      productBarCode: '10012000006',
      productUnitName: '个',
      stockCount: null,
      productBrandName: 'nike',
      productPicUrl: null,
      productStandard: 'SE32X125',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7571,
          valueName: '125mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: '不知道',
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 70,
      productId: 2105,
      productUnitId: 22,
      productPrice: 277,
      orderProductPrice: 297.36,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 108.03,
      totalPrice: 939.03,
      remark: null,
      outCount: 3,
      returnCount: 0,
      productName: '914',
      productBarCode: '10012000014',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X300',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7581,
          valueName: '300mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
    {
      id: 69,
      productId: 2106,
      productUnitId: 22,
      productPrice: 312,
      orderProductPrice: 334.93,
      count: 3,
      discountPercent: 0,
      discountPrice: 0,
      taxPercent: 13,
      taxPrice: 121.68,
      totalPrice: 1057.68,
      remark: null,
      outCount: 0,
      returnCount: 0,
      productName: '916',
      productBarCode: '10012000016',
      productUnitName: '个',
      stockCount: null,
      productBrandName: null,
      productPicUrl: null,
      productStandard: 'SE32X400',
      warehouseId: 6,
      properties: [
        {
          propertyId: 46,
          propertyName: '系列',
          valueId: 7653,
          valueName: 'SE',
        },
        {
          propertyId: 57,
          propertyName: '缸径',
          valueId: 7654,
          valueName: '32mm',
        },
        {
          propertyId: 59,
          propertyName: '活塞杆材质',
          valueId: 7656,
          valueName: '中碳钢',
        },
        {
          propertyId: 58,
          propertyName: '行程',
          valueId: 7583,
          valueName: '400mm',
        },
        {
          propertyId: 60,
          propertyName: '可调行程',
          valueId: 7657,
          valueName: '-',
        },
        {
          propertyId: 61,
          propertyName: '磁环',
          valueId: 7658,
          valueName: '无',
        },
        {
          propertyId: 62,
          propertyName: '固定式',
          valueId: 7659,
          valueName: '-',
        },
        {
          propertyId: 63,
          propertyName: '密封件',
          valueId: 7660,
          valueName: 'TPU',
        },
        {
          propertyId: 54,
          propertyName: '螺纹种类',
          valueId: 149,
          valueName: 'Rc/PT',
        },
      ],
      auxiliaryUnits: null,
    },
  ],
  printDate: '2025-02-11 15:25:28',
};
