/*
 * @Description:
 * @Author: CcSimple
 * @Github: https://github.com/CcSimple
 * @Date: 2023-02-09 10:40:26
 * @LastEditors: CcSimple
 * @LastEditTime: 2023-02-09 10:50:02
 */
import { hiprint } from 'vue-plugin-hiprint';

export const provider2 = function (options) {
  const addElementTypes = function (context) {
    context.removePrintElementTypes('providerModule2');
    context.addPrintElementTypes('providerModule2', [
      new hiprint.PrintElementTypeGroup('表格', [
        {
          tid: 'providerModule2.table',
          title: '订单数据',
          type: 'table',
          options: {
            field: 'table',
            fields: [
              { text: '序号', field: 'rowIndex', width: 60 },
              { text: '产品名称', field: 'productName' },
              { text: '型号', field: 'productStandard' },
              { text: '数量/单位', field: 'TM' },
              { text: '货期(工作日)', field: 'productPrice' },
              { text: '面价(元)', field: 'originalPrice' },
              { text: '单价(元)', field: 'productPrice' },
              { text: '金额(元)', field: 'totalPrice' },
              { text: '备注', field: 'remark' },
            ],
          },
          columns: [
            [
              {
                title: '序号',
                align: 'center',
                field: 'testIndex',
                width: 100,
                formatter(value, row, index) {
                  return `<span>${index + 1}</span>`;
                },
              },
              {
                title: '产品名称',
                align: 'center',
                field: 'productName',
                width: 100,
              },
              {
                title: '型号',
                align: 'center',
                field: 'productStandard',
                width: 100,
              },
              { title: '数量/单位', align: 'center', field: 'TM', width: 100 },
              {
                title: '货期(工作日)',
                align: 'center',
                field: 'productPrice',
                width: 100,
              },
              {
                title: '面价(元)',
                align: 'center',
                field: 'originalPrice',
                width: 100,
              },
              {
                title: '单价(元)',
                align: 'center',
                field: 'productPrice',
                width: 100,
              },
              {
                title: '金额(元)',
                align: 'center',
                field: 'totalPrice',
                width: 100,
              },
              { title: '备注', align: 'center', field: 'remark', width: 100 },
            ],
          ],
          footerFormatter(options, rows, data, pageData, pageIndex) {
            const styles = {
              noBorder: 'border: none !important',
              cell: 'padding: 8px; vertical-align: middle',
              rightAlign: 'text-align: right',
              centerAlign: 'text-align: center',
              borderBottom: 'border-bottom: none !important',
              borderRight: 'border-right: none  !important',
              borderTop: 'border-top: none !important',
            };

            return `
                    <tr>
                      <td colspan="2" style="${styles.borderBottom}">合计（元）</td>
                      <td colspan="7" style="${styles.cell}; ${styles.noBorder}; ${styles.centerAlign}">￥：${data?.totalPrice}</td>
                    </tr>
                    <tr style="${styles.noBorder};">
                      <td colspan="5" style="${styles.borderTop}; ${styles.borderBottom};${styles.noBorder}">价格有效期：${data?.validityPeriod}</td>
                      <td colspan="5" style="${styles.borderTop}; ${styles.borderBottom};${styles.noBorder}">付款方式：${data?.payType}</td>
                    </tr>
                    <tr style="${styles.noBorder};">
                      <td colspan="5" style="${styles.borderTop}; ${styles.borderBottom};${styles.noBorder}">发票类型：${data?.invoiceType}</td>
                      <td colspan="5" style="${styles.borderTop}; ${styles.borderBottom};${styles.noBorder}">产品配送运费：${data?.expressType}</td>
                    </tr>
                  `;
          },
        },

        {
          tid: 'providerModule2.table2',
          title: '销售出库',
          type: 'table',
          options: {
            field: 'items',
            fields: [
              { text: '序号', field: 'rowIndex', width: 60 },
              { text: '产品名称', field: 'productName' },
              { text: '型号', field: 'productStandard' },
              { text: '数量/单位', field: 'TM' },
              { text: '货期(工作日)', field: 'productPrice' },
              { text: '面价(元)', field: 'originalPrice' },
              { text: '单价(元)', field: 'productPrice' },
              { text: '金额(元)', field: 'totalPrice' },
              { text: '备注', field: 'remark' },
            ],
          },
          columns: [
            [
              {
                width: 14.924_496_355_733_648,
                title: '序号',
                field: 'testIndex',
                align: 'center',
                renderFormatter:
                  'function (value, row, colIndex, options,rowIndex) { return rowIndex+1;}',
                tableQRCodeLevel: 0,
                tableSummaryTitle: true,
                tableSummary: '',
              },
              {
                width: 90.545_846_090_209_04,
                title: '商品名称',
                field: 'productName',
                columnId: 'productName',
                align: 'center',
                tableQRCodeLevel: 0,
                tableSummaryTitle: true,
                tableSummaryText: '合计',
                tableSummaryColspan: '1',
                tableSummary: 'text',
              },
              {
                width: 65.727_645_085_472,
                title: '规格型号\n',
                field: 'productStandard',
                checked: true,
                columnId: 'productStandard',
                align: 'center',
                tableQRCodeLevel: 0,
                tableSummaryTitle: true,
                tableSummary: '',
              },
              {
                width: 48.352_080_887_105_1,
                title: '品牌\n',
                field: 'productBrandName',
                checked: true,
                columnId: 'productBrandName',
                fixed: false,
                rowspan: 1,
                colspan: 1,
                tableQRCodeLevel: 0,
                tableSummaryTitle: true,
                tableSummary: '',
              },
              {
                width: 40.136_353_894_819_95,
                title: '单位\n',
                field: 'productUnitName',
                checked: true,
                columnId: 'productUnitName',
                fixed: false,
                rowspan: 1,
                colspan: 1,
                align: 'center',
                tableQRCodeLevel: 0,
                tableSummaryTitle: true,
                tableSummaryColspan: '1',
                tableSummary: 'text',
              },
              {
                width: 42.415_161_636_315_83,
                title: '数量\n',
                field: 'count',
                checked: true,
                columnId: 'count',
                fixed: false,
                rowspan: 1,
                colspan: 1,
                align: 'center',
                tableQRCodeLevel: 0,
                tableSummaryTitle: true,
                tableSummaryText: ' ',
                tableSummaryColspan: '1',
                tableSummary: 'sum',
                tableSummaryAlign: 'center',
                tableSummaryNumFormat: '0',
              },
              {
                width: 50.040_046_154_125_09,
                title: '关联销售订单号',
                field: 'orderNo',
                checked: true,
                columnId: 'orderNo',
                fixed: false,
                rowspan: 1,
                colspan: 1,
                align: 'center',
                tableQRCodeLevel: 0,
                tableSummaryTitle: true,
                tableSummary: '',
              },
              {
                width: 50.040_046_154_125_09,
                title: '原价',
                field: 'originalPrice',
                checked: true,
                columnId: 'originalPrice',
                fixed: false,
                rowspan: 1,
                colspan: 1,
                align: 'center',
                tableQRCodeLevel: 0,
                tableSummaryTitle: true,
                tableSummary: '',
              },
              {
                width: 50.040_046_154_125_09,
                title: '折扣单价',
                field: 'productPrice',
                checked: true,
                columnId: 'productPrice',
                fixed: false,
                rowspan: 1,
                colspan: 1,
                align: 'center',
                tableQRCodeLevel: 0,
                tableSummaryTitle: true,
                tableSummary: '',
              },
              {
                width: 39.554_969_076_902_61,
                title: '折扣%',
                field: 'discountPercent',
                checked: true,
                columnId: 'discountPercent',
                fixed: false,
                align: 'center',
                rowspan: 1,
                colspan: 1,
                tableQRCodeLevel: 0,
                tableSummaryTitle: true,
                tableSummary: '',
              },
              {
                width: 60.340_217_824_017_06,
                title: '折扣金额',
                field: 'discountPrice',
                checked: true,
                columnId: 'discountPrice',
                fixed: false,
                align: 'center',
                rowspan: 1,
                colspan: 1,
                tableQRCodeLevel: 0,
                tableSummaryTitle: true,
                tableSummaryText: ' ',
                tableSummaryColspan: '1',
                tableSummary: 'sum',
              },
              {
                width: 68.963_182_995_299_63,
                title: '金额',
                field: 'totalPrice',
                checked: true,
                columnId: 'totalPrice',
                fixed: false,
                rowspan: 1,
                colspan: 1,
                align: 'center',
                tableQRCodeLevel: 0,
                tableSummaryTitle: false,
                tableSummaryColspan: '1',
                tableSummary: 'sum',
              },
              {
                width: 38.853_872_447_266_05,
                title: '备注\n',
                field: 'remark',
                checked: false,
                columnId: 'remark',
                fixed: false,
                rowspan: 1,
                colspan: 1,
                align: 'center',
                tableQRCodeLevel: 0,
                tableSummaryTitle: true,
                tableSummary: '',
              },
              {
                width: 48.172_940_418_679_616,
                title: '面价',
                field: 'originalPrice',
                checked: false,
                columnId: 'originalPrice',
                fixed: false,
                rowspan: 1,
                colspan: 1,
                tableQRCodeLevel: 0,
                tableSummaryTitle: true,
                tableSummary: '',
              },
              {
                width: 69.141_437_880_243_33,
                title: '单价(元)',
                field: 'productPrice',
                checked: false,
                columnId: 'productPrice',
                fixed: false,
                rowspan: 1,
                colspan: 1,
                align: 'center',
                tableQRCodeLevel: 0,
                tableSummaryTitle: true,
                tableSummary: '',
              },
              {
                width: 45.775_263_528_658_385,
                title: '数量',
                field: 'TM',
                checked: false,
                columnId: 'TM',
                fixed: false,
                rowspan: 1,
                colspan: 1,
                align: 'center',
                tableQRCodeLevel: 0,
                tableSummaryTitle: true,
                tableSummary: '',
              },
            ],
          ],
          footerFormatter:
            "function (options, rows, data, pageData, pageIndex) {let styles = {cell: 'padding: 8px; vertical-align: middle',centerAlign: 'text-align: center',centerLeft: 'text-align: left', borderRight: 'border-right: 1px solid black',};return `\n                    <tr>\n                      <td colspan=\"12\" style=\"${styles.cell};${styles.centerLeft};\">合计金额大写:  ${data?.totalPrice}</td>\n                    </tr>\n                  `;\n              }",
        },
      ]),
      new hiprint.PrintElementTypeGroup('客户', [
        {
          tid: 'customer.name',
          title: '甲方名称',
          data: '腾讯有限公司',
          type: 'text',
          options: {
            field: 'customer.name',
            testData: '腾讯有限公司',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },

        {
          tid: 'customer.contact',
          title: '甲方联系人',
          data: '腾讯有限公司',
          type: 'text',
          options: {
            field: 'customer.contact',
            testData: '腾讯有限公司',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'customer.telephone',
          title: '甲方电话',
          data: '18888888888',
          type: 'text',
          options: {
            field: 'customer.telephone',
            testData: '082-12354',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'customer.mobile',
          title: '甲方手机',
          data: '18888888888',
          type: 'text',
          options: {
            field: 'customer.mobile',
            testData: '18888888888',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'customer.email',
          title: '甲方邮箱',
          data: '18888888888',
          type: 'text',
          options: {
            field: 'customer.email',
            testData: '10086@qq.com',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'customer.fax',
          title: '客户传真',
          data: '0251-23564',
          type: 'text',
          options: {
            field: 'customer.fax',
            testData: '0251-23564',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'customer.deliveryAddress',
          title: '客户地址',
          data: '0251-23564',
          type: 'text',
          options: {
            field: 'customer.deliveryAddress',
            testData: '0251-23564',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },

        {
          tid: 'consigneeInfo.username',
          title: '客户收货人',
          data: 'RMB',
          type: 'text',
          options: {
            field: 'consigneeInfo.username',
            testData: '李四',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'consigneeInfo.mobile',
          title: '客户收货电话',
          data: 'RMB',
          type: 'text',
          options: {
            field: 'consigneeInfo.mobile',
            testData: '10086',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'consigneeInfo.address',
          title: '客户收货地址',
          data: 'RMB',
          type: 'text',
          options: {
            field: 'consigneeInfo.address',
            testData: '北京市东城区',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'customer.bankAccount',
          title: '收款账户',
          data: '16354564564',
          type: 'text',
          options: {
            field: 'customer.bankAccount',
            testData: '35415454',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
      ]),
      new hiprint.PrintElementTypeGroup('我方公司', [
        {
          tid: 'company.name',
          title: '乙方名称',
          data: '腾讯有限公司',
          type: 'text',
          options: {
            field: 'company.name',
            testData: '腾讯有限公司',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'company.contact',
          title: '乙方联系人',
          data: '腾讯有限公司',
          type: 'text',
          options: {
            field: 'company.contact',
            testData: '腾讯有限公司',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'company.telephone',
          title: '乙方电话',
          data: '18888888888',
          type: 'text',
          options: {
            field: 'company.telephone',
            testData: '082-12354',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'company.mobile',
          title: '乙方手机',
          data: '18888888888',
          type: 'text',
          options: {
            field: 'company.mobile',
            testData: '18888888888',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'company.email',
          title: '乙方邮箱',
          data: '18888888888',
          type: 'text',
          options: {
            field: 'company.email',
            testData: '10086@qq.com',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
      ]),
      new hiprint.PrintElementTypeGroup('销售出库', [
        {
          tid: 'saleUserName',
          title: '销售人员',
          data: '张三',
          type: 'text',
          options: {
            field: 'saleUserName',
            testData: '张三',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },

        {
          tid: 'discountPercent',
          title: '总优惠率',
          data: '10%',
          type: 'text',
          options: {
            field: 'discountPercent',
            testData: '10%',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'totalDiscountPrice',
          title: '总优惠金额',
          data: '100.00',
          type: 'text',
          options: {
            field: 'totalDiscountPrice',
            testData: '100.00',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'totalPrice',
          title: '本次收款',
          data: '100.00',
          type: 'text',
          options: {
            field: 'totalPrice',
            testData: '100.00',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'orderPrice',
          title: '销售费用',
          data: '200.00',
          type: 'text',
          options: {
            field: 'orderPrice',
            testData: '200.00',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'outUserName',
          title: '制单人',
          data: '制单人王五',
          type: 'text',
          options: {
            field: 'outUserName',
            testData: '制单人王五',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
      ]),
      new hiprint.PrintElementTypeGroup('提示/备注', [
        {
          tid: 'tips1',
          title: '备注一',
          data: '一丶质保期限:按照产品的质保条件及质保期对产品提供质保承诺。',
          type: 'text',
          options: {
            field: 'tips1',
            testData:
              '一丶质保期限:按照产品的质保条件及质保期对产品提供质保承诺。',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
        {
          tid: 'tips2',
          title: '备注2',
          data: '二丶由于我司库存变化较大，为了是您如期收到产品，请在订购前再次向您服务的产品工程师确认货期。如果其他任何问题或任何我司协助的事宜。',
          type: 'text',
          options: {
            field: 'tips2',
            testData:
              '二丶由于我司库存变化较大，为了是您如期收到产品，请在订购前再次向您服务的产品工程师确认货期。如果其他任何问题或任何我司协助的事宜。',
            height: 24,
            width: 562.5,
            fontSize: '9pt',
            textAlign: 'left',
            textContentVerticalAlign: 'middle',
          },
        },
      ]),
    ]);
  };
  return {
    addElementTypes,
  };
};
