// 基础A4纸张
export const basicTemplate = {
  "panels": [{
    "index": 0,
    "name": 1,
    "height": 297,
    "width": 210,
    "paperHeader": 16.5,
    "paperFooter": 813,
    "printElements": [],
    "paperNumberLeft": 300,
    "paperNumberTop": 816,
    "paperNumberContinue": true,
    "paperNumberFormat": "${paperNo}",
    "watermarkOptions": {
      "content": "",
      "fillStyle": "rgba(184, 184, 184, 0.3)",
      "fontSize": "14px",
      "rotate": 25,
      "width": 200,
      "height": 200,
      "timestamp": false,
      "format": "YYYY-MM-DD HH:mm"
    },
    "panelLayoutOptions": {"layoutType": "column", "layoutRowGap": 0, "layoutColumnGap": 0}
  }]
}

export const pkmTemplate = {
  "panels": [{
    "index": 0,
    "name": 1,
    "height": 297,
    "width": 210,
    "paperHeader": 16.5,
    "paperFooter": 813,
    "printElements": [{
      "options": {
        "left": 12.5,
        "top": 17.5,
        "height": 90,
        "width": 267,
        "right": 278.7421875,
        "bottom": 107.49609375,
        "vCenter": 145.2421875,
        "hCenter": 62.49609375,
        "field": "logo",
        "fit": "",
        "coordinateSync": false,
        "widthHeightSync": false,
        "src": "http://longfa-test.oss-cn-shenzhen.aliyuncs.com/6a906334fab5fa124556cac92a76ccbb8c7023d7dac001301d0083da0b3b8653.png"
      }, "printElementType": {"title": "Logo", "type": "image"}
    }, {
      "options": {
        "left": 399,
        "top": 36,
        "height": 31.5,
        "width": 160.5,
        "title": "工业品销售合同",
        "coordinateSync": false,
        "widthHeightSync": false,
        "fontSize": 20.25,
        "color": "#A9A9A9",
        "textContentVerticalAlign": "middle",
        "qrCodeLevel": 0,
        "right": 558.75,
        "bottom": 66.75,
        "vCenter": 478.5,
        "hCenter": 51
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 312.5,
        "top": 110,
        "height": 13.5,
        "width": 267,
        "title": "报价单号",
        "field": "no",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 460.74609375,
        "bottom": 123,
        "vCenter": 386.49609375,
        "hCenter": 116.25,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 312.5,
        "top": 130,
        "height": 13.5,
        "width": 267,
        "title": "报价日期",
        "field": "createTime",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 463.74609375,
        "bottom": 142.5,
        "vCenter": 389.49609375,
        "hCenter": 135.75,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 312.5,
        "top": 150,
        "height": 100.5,
        "width": 267,
        "right": 579.99609375,
        "bottom": 249,
        "vCenter": 446.49609375,
        "hCenter": 198.75,
        "coordinateSync": false,
        "widthHeightSync": false,
        "borderWidth": "0.75",
        "borderStyle": "solid",
        "borderColor": "#000000"
      }, "printElementType": {"title": "矩形", "type": "rect"}
    }, {
      "options": {
        "left": 17.5,
        "top": 150.75,
        "height": 100.5,
        "width": 267,
        "right": 285.73828125,
        "bottom": 254.98828125,
        "vCenter": 152.23828125,
        "hCenter": 204.73828125,
        "coordinateSync": false,
        "widthHeightSync": false,
        "borderWidth": "0.75",
        "borderStyle": "solid",
        "borderColor": "#000000"
      }, "printElementType": {"title": "矩形", "type": "rect"}
    }, {
      "options": {
        "left": 29,
        "top": 157.75,
        "height": 13.5,
        "width": 241.5,
        "title": "甲方",
        "field": "customerName",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 267.74359130859375,
        "bottom": 173.99360275268555,
        "vCenter": 146.99359130859375,
        "hCenter": 167.24360275268555,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 325,
        "top": 158.25,
        "height": 13.5,
        "width": 243,
        "title": "乙方：",
        "field": "saleUserName",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 476.2500228881836,
        "bottom": 302.25,
        "vCenter": 402.0000228881836,
        "hCenter": 295.5,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 29.5,
        "top": 177.75,
        "height": 12,
        "width": 241.5,
        "title": "联系人",
        "field": "sup_incharge",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 207.75,
        "bottom": 213,
        "vCenter": 133.5,
        "hCenter": 206.25,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 325,
        "top": 177.75,
        "height": 12,
        "width": 241.5,
        "title": "联系人",
        "field": "need_incharge",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 477.7500228881836,
        "bottom": 321.75,
        "vCenter": 403.5000228881836,
        "hCenter": 315.75,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 325,
        "top": 194.25,
        "height": 13.5,
        "width": 241.5,
        "title": "电话",
        "field": "need_phone",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 475.5000228881836,
        "bottom": 340.5,
        "vCenter": 401.2500228881836,
        "hCenter": 333.75,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 30,
        "top": 197.5,
        "height": 13.5,
        "width": 241.5,
        "title": "电话",
        "field": "sup_phone",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 208.74609375,
        "bottom": 228.24609375,
        "vCenter": 134.49609375,
        "hCenter": 221.49609375,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 325,
        "top": 210.75,
        "height": 13.5,
        "width": 241.5,
        "title": "手机",
        "field": "need_mobile",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 477.0000228881836,
        "bottom": 354.75,
        "vCenter": 402.7500228881836,
        "hCenter": 348,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 29.5,
        "top": 213.75,
        "height": 13.5,
        "width": 241.5,
        "title": "手机",
        "field": "sup_mobile",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 210.24776458740234,
        "bottom": 249.24778175354004,
        "vCenter": 135.99776458740234,
        "hCenter": 242.49778175354004,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 325,
        "top": 228.75,
        "height": 13.5,
        "width": 241.5,
        "title": "邮箱",
        "field": "need_email",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 506.9999771118164,
        "bottom": 248.24571990966797,
        "vCenter": 432.7499771118164,
        "hCenter": 241.49571990966797,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 29.5,
        "top": 231.75,
        "height": 13.5,
        "width": 241.5,
        "title": "邮箱",
        "field": "sup_email",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 210.24776458740234,
        "bottom": 267.24778068065643,
        "vCenter": 135.99776458740234,
        "hCenter": 260.49778068065643,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 17.5,
        "top": 260.25,
        "height": 13.5,
        "width": 562.5,
        "title": "尊敬的：",
        "field": "customerName",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 528,
        "bottom": 276,
        "vCenter": 270.75,
        "hCenter": 269.25,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 17.5,
        "top": 278.25,
        "height": 42,
        "width": 562.5,
        "title": "非常感谢您选择品控猫，作为领先的工品采购商，我们坚持以“客户第一”的经营理念，为您提供专业的选购服务，相信这次报价是我们进一步合作的开始。",
        "right": 571.5,
        "bottom": 322.5,
        "vCenter": 291,
        "hCenter": 301.5,
        "coordinateSync": false,
        "widthHeightSync": false,
        "hideTitle": true,
        "fontSize": 9
      }, "printElementType": {"title": "长文本", "type": "longText"}
    }, {
      "options": {
        "left": 17.5,
        "top": 332.5,
        "height": 97.5,
        "width": 562.5,
        "tableFooterRepeat": "last",
        "fields": [{"text": "名称", "field": "NAME"}, {"text": "数量", "field": "SL"}, {
          "text": "规格",
          "field": "GG"
        }, {"text": "条码", "field": "TM"}, {"text": "单价", "field": "DJ"}, {
          "text": "金额",
          "field": "JE"
        }],
        "field": "items",
        "tableHeaderRepeat": "first",
        "footerFormatter": "function (options, rows, data, pageData, pageIndex) {\n" +
          "                let styles = {\n" +
          "                  noBorder: 'border: none !important',\n" +
          "                  cell: 'padding: 8px; vertical-align: middle',\n" +
          "                  rightAlign: 'text-align: right',\n" +
          "                  centerAlign: 'text-align: center',\n" +
          "                  borderBottom: 'border-bottom: none !important',\n" +
          "                  borderRight: 'border-right: none  !important',\n" +
          "                  borderTop: 'border-top: none !important',\n" +
          "                };\n" +
          "\n" +
          "                return `\n" +
          "                    <tr>\n" +
          "                      <td colspan=\"2\" style=\"${styles.borderBottom}\">合计（元）</td>\n" +
          "                      <td colspan=\"7\" style=\"${styles.cell}; ${styles.noBorder}; ${styles.centerAlign}\">￥：${data?.totalPrice}</td>\n" +
          "                    </tr>\n" +
          "                    <tr style=\"${styles.noBorder};\">\n" +
          "                      <td colspan=\"5\" style=\"${styles.borderTop}; ${styles.borderBottom};${styles.noBorder}\">价格有效期：${data?.expireTime}</td>\n" +
          "                      <td colspan=\"5\" style=\"${styles.borderTop}; ${styles.borderBottom};${styles.noBorder}\">付款方式：${data?.payType}</td>\n" +
          "                    </tr>\n" +
          "                    <tr style=\"${styles.noBorder};\">\n" +
          "                      <td colspan=\"5\" style=\"${styles.borderTop}; ${styles.borderBottom};${styles.noBorder}\">发票类型：${data?.invoiceType}</td>\n" +
          "                      <td colspan=\"5\" style=\"${styles.borderTop}; ${styles.borderBottom};${styles.noBorder}\">产品配送运费：${data?.expressType}</td>\n" +
          "                    </tr>\n" +
          "                  `;\n" +
          "\n" +
          "              }",
        "right": 579,
        "bottom": 430.2421875,
        "vCenter": 297.75,
        "hCenter": 381.4921875,
        "coordinateSync": false,
        "widthHeightSync": false,
        "tableHeaderBackground": "#f4cd0000",
        "fontSize": 8,
        "tableHeaderCellBorder": "border",
        "tableBodyRowBorder": "border",
        "tableBodyCellBorder": "border",
        "tableFooterBorder": "border",
        "tableFooterCellBorder": "border",
        "styler": "function(value, options, target,templateData){return '{'background':'red'}}",
        "columns": [[{
          "width": 19.550413786017593,
          "title": "序号",
          "field": "index",
          "checked": true,
          "columnId": "index",
          "fixed": false,
          "rowspan": 1,
          "colspan": 1,
          "align": "center",
          "tableColumnHeight": "50px",
          "tableQRCodeLevel": 0,
          "tableSummaryTitle": true,
          "tableSummary": "",
          "styler": "function(value)",
          "formatter2":"function (value, row, index) { return index + 1;}",
          }, {
          "width": 114.64943809175982,
          "title": "产品名称\n",
          "field": "productName",
          "checked": true,
          "columnId": "productName",
          "fixed": false,
          "rowspan": 1,
          "colspan": 1,
          "align": "center",
          "tableQRCodeLevel": 0,
          "tableSummaryTitle": true,
          "tableSummary": ""
        }, {
          "width": 63.87901758344935,
          "title": "型号\n",
          "field": "productStandard",
          "checked": true,
          "columnId": "model",
          "fixed": false,
          "rowspan": 1,
          "colspan": 1,
          "align": "center",
          "tableQRCodeLevel": 0,
          "tableSummaryTitle": true,
          "tableSummary": ""
        }, {
          "width": 58.85929431384312,
          "title": "数量/单位\n",
          "field": "numUnit",
          "checked": true,
          "columnId": "numUnit",
          "fixed": false,
          "rowspan": 1,
          "colspan": 1,
          "align": "center",
          "tableQRCodeLevel": 0,
          "tableSummaryTitle": true,
          "tableSummary": "",
          "formatter2":"function (value, row, index) { return `${row.count} / ${row.productUnitName}`;}",
        }, {
          "width": 62.13947502209974,
          "title": "交货日期",
          "field": "deliveryTime",
          "checked": true,
          "columnId": "goodsTime",
          "fixed": false,
          "rowspan": 1,
          "colspan": 1,
          "align": "center",
          "tableQRCodeLevel": 0,
          "tableSummaryTitle": true,
          "tableSummary": ""
        }, {
          "width": 48.09693613653128,
          "title": "面价(元)\t\n",
          "field": "productPrice",
          "checked": true,
          "columnId": "carrying",
          "fixed": false,
          "rowspan": 1,
          "colspan": 1,
          "align": "center",
          "tableQRCodeLevel": 0,
          "tableSummaryTitle": true,
          "tableSummary": ""
        }, {
          "width": 46.05797502209973,
          "title": "单价(元)\n",
          "field": "orderProductPrice",
          "checked": true,
          "columnId": "productPrice",
          "fixed": false,
          "rowspan": 1,
          "colspan": 1,
          "align": "center",
          "tableQRCodeLevel": 0,
          "tableSummaryTitle": true,
          "tableSummary": ""
        }, {
          "width": 44.02922502209957,
          "title": "金额(元)\n",
          "field": "totalPrice",
          "checked": true,
          "columnId": "totalPrice",
          "fixed": false,
          "rowspan": 1,
          "colspan": 1,
          "align": "center",
          "tableQRCodeLevel": 0,
          "tableSummaryTitle": true,
          "tableSummary": ""
        }, {
          "width": 105.2382250220998,
          "title": "备注\n",
          "field": "remark",
          "checked": true,
          "columnId": "des",
          "fixed": false,
          "rowspan": 1,
          "colspan": 1,
          "align": "center",
          "tableQRCodeLevel": 0,
          "tableSummaryTitle": true,
          "tableSummary": ""
        }, ]]
      },
      "printElementType": {
        "title": "订单数据",
        "type": "table",
        "editable": true,
        "columnDisplayEditable": true,
        "columnDisplayIndexEditable": true,
        "columnTitleEditable": true,
        "columnResizable": true,
        "columnAlignEditable": true,
        "isEnableEditField": true,
        "isEnableContextMenu": true,
        "isEnableInsertRow": true,
        "isEnableDeleteRow": true,
        "isEnableInsertColumn": true,
        "isEnableDeleteColumn": true,
        "isEnableMergeCell": true
      }
    }, {
      "options": {
        "left": 310,
        "top": 555,
        "height": 13.5,
        "width": 267,
        "title": "乙方",
        "field": "need_company",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 573.9928665161133,
        "bottom": 538.7428665161133,
        "vCenter": 440.4928665161133,
        "hCenter": 531.9928665161133,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 15,
        "top": 555,
        "height": 13.5,
        "width": 267,
        "title": "甲方",
        "field": "sup_company",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 254.74644470214844,
        "bottom": 538.4999771118164,
        "vCenter": 133.99644470214844,
        "hCenter": 531.7499771118164,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 307.5,
        "top": 580,
        "height": 42,
        "width": 127.5,
        "right": 428.25,
        "bottom": 589.5,
        "vCenter": 364.5,
        "hCenter": 568.5,
        "field": "seal",
        "fit": "",
        "coordinateSync": false,
        "widthHeightSync": false,
        "src": "http://longfa-test.oss-cn-shenzhen.aliyuncs.com/db8bfb67a5b977383e8f6f18b40b33a790a37471e10032bd79e7b73add7292a2.png"
      }, "printElementType": {"title": "Logo", "type": "image"}
    }, {
      "options": {
        "left": 310,
        "top": 590,
        "height": 9.75,
        "width": 123,
        "title": "文本",
        "right": 432.74356842041016,
        "bottom": 569.2435913085938,
        "vCenter": 371.24356842041016,
        "hCenter": 564.3685913085938,
        "field": "need_company_incharge",
        "coordinateSync": false,
        "widthHeightSync": false,
        "textAlign": "center",
        "textContentVerticalAlign": "middle",
        "textContentWrap": "nowrap",
        "qrCodeLevel": 0,
        "hideTitle": true,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 160,
        "top": 590,
        "height": 9.75,
        "width": 123,
        "title": "文本",
        "right": 281.4928894042969,
        "bottom": 567.75,
        "vCenter": 219.99288940429688,
        "hCenter": 562.875,
        "field": "sup_date",
        "coordinateSync": false,
        "widthHeightSync": false,
        "textAlign": "center",
        "textContentVerticalAlign": "middle",
        "textContentWrap": "nowrap",
        "qrCodeLevel": 0,
        "hideTitle": true,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 452.5,
        "top": 590,
        "height": 9.75,
        "width": 123,
        "title": "文本",
        "right": 573.24609375,
        "bottom": 600.75,
        "vCenter": 511.74609375,
        "hCenter": 595.875,
        "field": "need_date",
        "coordinateSync": false,
        "widthHeightSync": false,
        "textAlign": "center",
        "textContentVerticalAlign": "middle",
        "textContentWrap": "nowrap",
        "qrCodeLevel": 0,
        "hideTitle": true,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 15,
        "top": 590,
        "height": 9.75,
        "width": 123,
        "title": "文本",
        "right": 138.7499771118164,
        "bottom": 569.7464447021484,
        "vCenter": 77.2499771118164,
        "hCenter": 564.8714447021484,
        "field": "sup_company_incharge",
        "coordinateSync": false,
        "widthHeightSync": false,
        "textAlign": "center",
        "textContentVerticalAlign": "middle",
        "textContentWrap": "nowrap",
        "qrCodeLevel": 0,
        "hideTitle": true,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 310,
        "top": 602.5,
        "height": 13.5,
        "width": 123,
        "title": "授权人签字盖章",
        "right": 427.5,
        "bottom": 585.75,
        "vCenter": 366,
        "hCenter": 579,
        "coordinateSync": false,
        "widthHeightSync": false,
        "textAlign": "center",
        "textContentVerticalAlign": "middle",
        "qrCodeLevel": 0,
        "hideTitle": true,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 452.5,
        "top": 602.5,
        "height": 13.5,
        "width": 123,
        "right": 572.25,
        "bottom": 587.25,
        "vCenter": 510.75,
        "hCenter": 580.5,
        "coordinateSync": false,
        "widthHeightSync": false,
        "textAlign": "center",
        "textContentVerticalAlign": "middle",
        "qrCodeLevel": 0,
        "title": "日期",
        "hideTitle": true,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 160,
        "top": 605,
        "height": 13.5,
        "width": 123,
        "right": 281.2499771118164,
        "bottom": 583.4999542236328,
        "vCenter": 219.7499771118164,
        "hCenter": 578.6249542236328,
        "coordinateSync": false,
        "widthHeightSync": false,
        "textAlign": "center",
        "textContentVerticalAlign": "middle",
        "qrCodeLevel": 0,
        "title": "日期",
        "hideTitle": true,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 15,
        "top": 605,
        "height": 13.5,
        "width": 123,
        "title": "授权人签字盖章",
        "right": 137.49288940429688,
        "bottom": 587.25,
        "vCenter": 75.99288940429688,
        "hCenter": 582.375,
        "coordinateSync": false,
        "widthHeightSync": false,
        "textAlign": "center",
        "textContentVerticalAlign": "middle",
        "qrCodeLevel": 0,
        "hideTitle": true,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 15,
        "top": 625,
        "height": 81,
        "width": 268.5,
        "right": 281.74644470214844,
        "bottom": 687.4964447021484,
        "vCenter": 147.49644470214844,
        "hCenter": 642.4964447021484,
        "coordinateSync": false,
        "widthHeightSync": false,
        "borderWidth": "0.75",
        "borderStyle": "solid",
        "borderColor": "#000000"
      }, "printElementType": {"title": "矩形", "type": "rect"}
    }, {
      "options": {
        "left": 310,
        "top": 625,
        "height": 81,
        "width": 268.5,
        "right": 401.4928665161133,
        "bottom": 684.7499542236328,
        "vCenter": 356.4928665161133,
        "hCenter": 639.7499542236328,
        "coordinateSync": false,
        "widthHeightSync": false,
        "borderWidth": "0.75",
        "borderStyle": "solid",
        "borderColor": "#000000"
      }, "printElementType": {"title": "矩形", "type": "rect"}
    }, {
      "options": {
        "left": 27.5,
        "top": 635,
        "height": 13.5,
        "width": 241.5,
        "title": "账户名称",
        "field": "sup_company",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 267.74356842041016,
        "bottom": 618.7478256225586,
        "vCenter": 146.99356842041016,
        "hCenter": 611.9978256225586,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 322.5,
        "top": 635,
        "height": 13.5,
        "width": 241.5,
        "title": "开户行",
        "field": "need_company",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 538.74609375,
        "bottom": 765.99609375,
        "vCenter": 417.99609375,
        "hCenter": 759.24609375,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 322.5,
        "top": 652.5,
        "height": 13.5,
        "width": 241.5,
        "title": "账户名称",
        "field": "need_company_bbk",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 537.75,
        "bottom": 747.99609375,
        "vCenter": 417,
        "hCenter": 741.24609375,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 27.5,
        "top": 652.5,
        "height": 13.5,
        "width": 241.5,
        "title": "开户行",
        "field": "sup_company_bbk",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 266.9978713989258,
        "bottom": 635.9935684204102,
        "vCenter": 146.24787139892578,
        "hCenter": 629.2435684204102,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 322.5,
        "top": 670,
        "height": 13.5,
        "width": 241.5,
        "title": "账号",
        "field": "need_company_bbk_num",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 537.99609375,
        "bottom": 766.2421875,
        "vCenter": 417.24609375,
        "hCenter": 759.4921875,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 27.5,
        "top": 670,
        "height": 13.5,
        "width": 241.5,
        "title": "账号",
        "field": "sup_company_bbk_num",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 269.24356842041016,
        "bottom": 652.4935684204102,
        "vCenter": 148.49356842041016,
        "hCenter": 645.7435684204102,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 27.5,
        "top": 685,
        "height": 13.5,
        "width": 241.5,
        "title": "税号",
        "field": "sup_company_sh",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 266.4928894042969,
        "bottom": 668.4928894042969,
        "vCenter": 145.74288940429688,
        "hCenter": 661.7428894042969,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 322.5,
        "top": 685,
        "height": 13.5,
        "width": 241.5,
        "title": "税号",
        "field": "need_company_sh",
        "coordinateSync": false,
        "widthHeightSync": false,
        "qrCodeLevel": 0,
        "right": 537.4921875,
        "bottom": 780.24609375,
        "vCenter": 416.7421875,
        "hCenter": 773.49609375,
        "fontSize": 9
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 17.5,
        "top": 452.5,
        "height": 16.5,
        "width": 562.5,
        "title": "文本",
        "right": 580.74609375,
        "bottom": 468.99609375,
        "vCenter": 299.49609375,
        "hCenter": 460.74609375,
        "field": "ps1",
        "testData": "一丶质保期限:按照产品的质保条件及质保期对产品提供质保承诺。",
        "coordinateSync": false,
        "widthHeightSync": false,
        "hideTitle": true,
        "fontSize": 9,
        "qrCodeLevel": 0
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 17.5,
        "top": 470,
        "height": 24,
        "width": 562.5,
        "title": "文本",
        "right": 580.5,
        "bottom": 490.5,
        "vCenter": 299.25,
        "hCenter": 482.25,
        "field": "ps2",
        "testData": "二丶由于我司库存变化较大，为了是您如期收到产品，请在订购前再次向您服务的产品工程师确认货期。如果其他任何问题或任何我司协助的事宜。",
        "coordinateSync": false,
        "widthHeightSync": false,
        "hideTitle": true,
        "fontSize": 9,
        "qrCodeLevel": 0
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 17.5,
        "top": 497.5,
        "height": 16.5,
        "width": 562.5,
        "title": "文本",
        "right": 579.99609375,
        "bottom": 513.99609375,
        "vCenter": 298.74609375,
        "hCenter": 505.74609375,
        "field": "ps3",
        "testData": "三丶有任何问题请联系我们。",
        "coordinateSync": false,
        "widthHeightSync": false,
        "hideTitle": true,
        "fontSize": 9,
        "qrCodeLevel": 0
      }, "printElementType": {"title": "文本", "type": "text"}
    }, {
      "options": {
        "left": 17.5,
        "top": 515,
        "height": 16.5,
        "width": 562.5,
        "title": "文本",
        "right": 578.25,
        "bottom": 531.75,
        "vCenter": 297,
        "hCenter": 523.5,
        "field": "ps",
        "testData": "备注：贵司同意书上述价格和条款，请及时与您服务的客户经理联系，签订正式合同。",
        "coordinateSync": false,
        "widthHeightSync": false,
        "hideTitle": true,
        "fontSize": 9,
        "qrCodeLevel": 0
      }, "printElementType": {"title": "文本", "type": "text"}
    }],
    "paperNumberLeft": 300,
    "paperNumberTop": 816,
    "paperNumberContinue": true,
    "paperNumberFormat": "${paperNo}",
    "watermarkOptions": {
      "content": "",
      "fillStyle": "rgba(184, 184, 184, 0.3)",
      "fontSize": "14px",
      "rotate": 25,
      "width": 200,
      "height": 200,
      "timestamp": false,
      "format": "YYYY-MM-DD HH:mm"
    },
    "panelLayoutOptions": {"layoutType": "column", "layoutRowGap": 0, "layoutColumnGap": 0}
  }]
}
