name: CI Github Pages

on:
  push:
    branches:
      - dev  # 监听dev分支的push操作

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.9.0'  # 指定所需的 Node.js 版本

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install and Build
        run: |
          cd apps/web-ele
          pnpm install
          pnpm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages  # 部署后提交到新的分支
          folder: apps/web-ele/dist  # 打包后的目录路径
          token: ${{ secrets.GITHUB_TOKEN }}
